name: ML Pipeline CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Data Preprocessing
      run: python scripts/preprocess_data.py

    - name: Train Model
      run: python scripts/train_model.py

    - name: Commit Model to Repository
      run: |
        git add models/*
        git commit -m "Update trained model"
        git push
